#!/usr/bin/env python3
import sys
import subprocess
from pathlib import Path

if len(sys.argv) < 2:
    print("Usage: tarm <archive.tar.gz>")
    sys.exit(1)

arg = sys.argv[1]

if arg in ("--version", "-v"):
    print("Tarm - TAR.REMOVE v1.1")
    print("Build on 9/2/2026")
    print("by spaceguythe1 on github :)")
    sys.exit(0)

archive = Path(sys.argv[1]).expanduser()

if not archive.is_file(): #OTHER COMMANDS
    print("Not a file.")
    sys.exit(1)

archive = archive.resolve()

print(f"Extracting {archive}")

subprocess.run(
    ["tar", "-xzvf", str(archive)],
    cwd=archive.parent,          # 👈 critical line
    stdin=subprocess.DEVNULL,
    check=True
)

archive.unlink()
print("Archive removed")
